backend:
  name: github
  repo: weisslabmit/lab-website
  branch: main
  base_url: https://weisslab-cms-oauth.onrender.com
  auth_endpoint: /auth

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "sanity"
    label: "Sanity"
    folder: "content/sanity"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
