backend:
  name: github
  repo: weisslabmit/lab-website
  branch: main
  base_url: https://weisslab-cms-oauth.onrender.com
  auth_endpoint: /auth

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "people"
    label: "People"
    folder: "content/people"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Role", name: "role", widget: "string", required: false }
      - { label: "Category", name: "category", widget: "select", required: false,
          options: ["PI", "Staff", "PhD Students", "Postdocs", "Other", "Undergrads"] }
      - { label: "Summary", name: "summary", widget: "text", required: false }
      - { label: "Email", name: "email", widget: "string", required: false }
      - { label: "Website", name: "website", widget: "string", required: false }
      - { label: "Google Scholar", name: "scholar", widget: "string", required: false }
      - { label: "GitHub", name: "github", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Weight (ordering)", name: "weight", widget: "number", required: false }


  - name: "research"
    label: "Research Topics"
    folder: "content/research"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Weight (order)", name: "weight", widget: "number", default: 1, min: 1, step: 1, required: false }
      - { label: "Summary", name: "summary", widget: "text", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
