backend:
  name: github
  repo: weisslabmit/lab-website
  branch: main
  base_url: https://weisslab-cms-oauth.onrender.com
  auth_endpoint: /auth

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "research"
    label: "Research Topics"
    folder: "content/research"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Weight (order)", name: "weight", widget: "number", default: 1, min: 1, step: 1 }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Image", name: "image", widget: "image", allow_multiple: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }

  - name: "people"
    label: "People"
    file: "data/people.yml"
    fields:
      - label: "People"
        name: "people"
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Role", name: "role", widget: "string", required: false }
          - { label: "Photo", name: "photo", widget: "image" }
          - { label: "Email", name: "email", widget: "string", required: false }
          - { label: "Website", name: "website", widget: "string", required: false }
          - { label: "Google Scholar", name: "scholar", widget: "string", required: false }
          - { label: "GitHub", name: "github", widget: "string", required: false }
          - { label: "Bio", name: "bio", widget: "text", required: false }