backend:
  name: github
  repo: weisslabmit/lab-website
  branch: main
  base_url: https://weisslab-cms-oauth.onrender.com
  auth_endpoint: /auth

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "people"
    label: "People"
    folder: "content/people"
    extension: "md"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    sortable_fields: ["title", "role", "weight"]
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - label: "Role"
        name: "role"
        widget: "select"
        options:
          - { label: "PI", value: "PI" }
          - { label: "Staff", value: "Staff" }
          - { label: "PhD student", value: "PhD" }
          - { label: "Postdoc", value: "Postdoc" }
          - { label: "Other", value: "Other" }
          - { label: "Undergrad", value: "Undergrad" }
        default: "Other"
      - { label: "Short description", name: "short", widget: "text", required: false }
      - { label: "Co-supervised by", name: "co_supervised_by", widget: "string", required: false }
      - { label: "Email", name: "email", widget: "string", required: false }
      - { label: "Website URL", name: "website", widget: "string", required: false }
      - { label: "Google Scholar URL", name: "scholar", widget: "string", required: false }
      - { label: "GitHub URL", name: "github", widget: "string", required: false }
      - { label: "ORCID URL", name: "orcid", widget: "string", required: false }
      - { label: "Photo", name: "image", widget: "image", required: false }
      # Education
      - { label: "PhD University", name: "phd_university", widget: "string", required: false }
      - { label: "PhD Date", name: "phd_date", widget: "string", required: false }
      - { label: "BS University", name: "bs_university", widget: "string", required: false }
      - { label: "BS Date", name: "bs_date", widget: "string", required: false }
      # Experience & Bio
      - { label: "Other experience (Markdown)", name: "experience", widget: "markdown", required: false }
      - { label: "Bio (Markdown)", name: "bio", widget: "markdown", required: false }
      - { label: "Weight (order within role)", name: "weight", widget: "number", required: false, default: 10 }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }



  - name: "research"
    label: "Research Topics"
    folder: "content/research"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Weight (order)", name: "weight", widget: "number", default: 1, min: 1, step: 1, required: false }
      - { label: "Summary", name: "summary", widget: "text", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
